name: Python 3.9, Java 15, .NET 5, allure

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install pylint
        # pip install flake8 pytest
        # pip install allure-pytest
        # sudo apt-add-repository ppa:qameta/allure
        # sudo apt-get update 
        sudo apt-get install allure
        mkdir allure-results
        mkdir allure-report
        mkdir allure-history
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      if: always()
      run: |
        pytest --alluredir=allure-results
#     - name: Analysing the code with pylint
#       run: |
#         pylint `ls -R|grep .py$|xargs`

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      if: always()
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Gradle wrapper
      if: always()
      run: gradle wrapper
    - name: Gradle version
      if: always()
      run: gradle --version
    - name: Grant execute permission for gradlew
      if: always()
      run: chmod +x gradlew
    - name: Build with Gradle
      if: always()
      run: ./gradlew build

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      if: always()
      with:
        dotnet-version: 5.0.x
    - name: dotnet version
      if: always()
      run: dotnet --version
    - name: Restore dependencies
      if: always()
      run: dotnet restore
    - name: Build
      if: always()
      run: dotnet build --no-restore
    - name: Test
      if: always()
      run: dotnet test --no-build --verbosity normal

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report with history
      uses: simple-elf/allure-report-action@v1.5

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
